spring:
  datasource:
    url: "jdbc:postgresql://mpglpostgresql.postgres.database.azure.com:5432/flight_inventory"
    username: "ayoubElmahjoubi"
    password: "waktir-wubxij-Hamvi2"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: ayoub
    password: ayoub
    properties:
       mail:
         smtp:
           trust: "*"
         auth: true
         starttls:
           enable: true
         connexiontimeout: 5000
         timeout: 3000
         writetimeout: 5000

  application:
    security:
      jwt:
        secret-key: cddd4adecfaad4016ce03a65e75a5dceb98d9361952ad1127105382564e3e3ad32d270ac15af7f8fbc2915d0b6c7d34395ecef53d7e4149f402f92ddadb3b5f3
        expiration: 8640000
    mailing:
      frontend:
        activation-url: http://localhost:3000/activate-account

server:
  port: 8088

