spring:
  datasource:
    url: database url
    username: database username
    password: database password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: ayoub
    password: ayoub
    properties:
       mail:
         smtp:
           trust: "*"
         auth: true
         starttls:
           enable: true
         connexiontimeout: 5000
         timeout: 3000
         writetimeout: 5000

  application:
    security:
      jwt:
        secret-key: put here a secret code so your hmac algo can using to generate JWT
        expiration: 8640000
    mailing:
      frontend:
        activation-url: http://localhost:3000/activate-account

server:
  port: 8088

